### ISSUE TITLE
Проблемы с установкой

### ISSUE THREAD

**Issue by webtotma** [shagabutdinov/sublime-goto-character#1]
После установки плагина ловлю окно: dependency import failed.

В описании плагина зависимостей нет.

ЧЯДНТ?

**Comment by webtotma** [comment]
Глянул в код

``` python
  from Expression import expression
except ImportError:
  sublime.error_message("Dependency import failed; please read readme for " +
   "GotoCharacter plugin for installation instructions; to disable this " +
   "message remove this plugin")
```

Получается необходим плагин Expression?

**Comment by shagabutdinov** [comment]
Да, всё верно. Установите плагин Expression и всё должно заработать.

## 

Leonid Shagabutdinov, CTO
idfly.ru, +7 905 937 6988
