### ISSUE TITLE
I created a goto-regex version

### ISSUE THREAD

**Issue by Ivanca** [shagabutdinov/sublime-goto-character#4]
https://github.com/Ivanca/sublime-goto-regex

I needed a goto-regex plugin, so I just changed the `re.escape (character)` part for `character` instead; that way I can use it with regex from key bindings, as in:
```json
  {
    "keys": ["alt+down"],
    "command": "goto_character",
    "args": {
      "character": "\\{|\\}"
    }
  }
 ```

(Created this issue just for reference/linking)

**Comment by shagabutdinov** [comment]
This looks like "goto expression" plugin, here is usage example: https://github.com/shagabutdinov/sublime-expression/blob/master/macro/goto_in_nesting_forward.sublime-macro

Goto expression was intended to provide smart code navigation (like selection inside brackets and etc.) and may look complex at first glance but it is stable and works well.
